id = "lydia"
name = "Lydia Theme"
version = "0.0.3"
schema_version = 1
authors = ["dnlytras <hi@dnlytras.com>"]
repository = "https://github.com/dimitrisnl/lydia-zed-theme"
description = "A dark color scheme built around cool blue-grays and vibrant accents."
